export const estados = [
    { name: 'Oaxaca' },
    { name: 'Puebla' },
]

export const ciudades = [
    { name: 'Cholula' },
    { name: 'Ciudad de puebla' },
]

export const zonas = [
    { name: 'Oaxaca Norte' },
    { name: 'Oaxaca Centro' },
    { name: 'Oaxaca Sur' },
]

export const tipoClientes = [
    { name: 'A' },
    { name: 'B' },
    { name: 'C' },
]

export const newCliente = {
  isActiveClient: 1,
  name: 'Default Name',
  taxId: 'XAXX010101000',
  street: 'Fixed Street',
  exteriorNumber: '123',
  interiorNumber: '',
  neighborhood: 'Centro',
  state: 'Oaxaca',
  city: 'Cholula',
  municipality: '',
  postalCode: 68000,
  phone: '9511234567',
  email: 'correo@ejemplo.com',
  consignmentPriceICC: '1000',
  latitude: '',
  longitude: '',
  zoneId: 'Oaxaca Centro',
  businessType: 'Comercial',
  reference: 'Default reference',
  hasPhoto: 0,
  isCommercial: 1,
  subBranchTypeId: 'A',
};


export const clientes = [
  {
    clienteactivo: 'true',
    nombre: 'Empresa Uno',
    rfc: 'RFC123456789',
    calle: 'Calle 1',
    numexterior: '100',
    numinterior: 'A',
    colonia: 'Centro',
    estado: 'Oaxaca',
    ciudad: 'Cholula',
    municipio: 'Benito Juárez',
    cp: '01234',
    telefono: '5512345678',
    correo: 'contacto@empresauno.com',
    precioconsigna: '1000',
    latitud: '',
    longitud: '',
    idzona: 'Oaxaca Centro',
    giro: 'Comercial',
    clasificacion: 'A',
    referencia: '',
    isfoto: undefined,
    iscomercial: undefined
  },
  {
    clienteactivo: 'false',
    nombre: 'Empresa Dos',
    rfc: 'RFC987654321',
    calle: 'Avenida 5',
    numexterior: '200',
    numinterior: 'B',
    colonia: 'Roma Norte',
    estado: 'Oaxaca',
    ciudad: 'Cholula',
    municipio: 'Cuauhtémoc',
    cp: '56789',
    telefono: '5598765432',
    correo: 'ventas@empresados.com',
    precioconsigna: '800',
    latitud: '',
    longitud: '',
    idzona: 'Oaxaca Sur',
    giro: 'Industrial',
    clasificacion: 'B',
    referencia: '',
    isfoto: undefined,
    iscomercial: undefined
  },
  {
    clienteactivo: 'true',
    nombre: 'Empresa Tres',
    rfc: 'RFC111222333',
    calle: 'Calle Reforma',
    numexterior: '350',
    numinterior: 'C',
    colonia: 'Del Valle',
    estado: 'Oaxaca',
    ciudad: 'Cholula',
    municipio: 'Benito Juárez',
    cp: '04567',
    telefono: '5533344455',
    correo: 'info@empresatres.com',
    precioconsigna: '1200',
    latitud: '',
    longitud: '',
    idzona: 'Oaxaca Sur',
    giro: 'Servicios',
    clasificacion: 'A',
    referencia: '',
    isfoto: undefined,
    iscomercial: undefined
  },
  {
    clienteactivo: 'false',
    nombre: 'Empresa Cuatro',
    rfc: 'RFC444555666',
    calle: 'Av. Insurgentes',
    numexterior: '450',
    numinterior: 'D',
    colonia: 'Napoles',
    estado: 'Oaxaca',
    ciudad: 'Cholula',
    municipio: 'Benito Juárez',
    cp: '03810',
    telefono: '5544455566',
    correo: 'contacto@empresacuatro.com',
    precioconsigna: '900',
    latitud: '-21.2455154151',
    longitud: '',
    idzona: 'Oaxaca Norte',
    giro: 'Comercial',
    clasificacion: 'C',
    referencia: '',
    isfoto: undefined,
    iscomercial: undefined
  }
];
